service: d-reader-backend
image: bdeak4/d-reader-backend

servers:
  monitoring:
    traefik: true
    hosts:
      - 5.75.167.62
    healthcheck:
      cmd: exit 0
    cmd: tail -f /dev/null

registry:
  server: ghcr.io
  username: bdeak4
  password:
    - MRSK_REGISTRY_PASSWORD

builder:
  multiarch: false

env:
  clear:
    PORT: 3005
  secret:
    - DATABASE_URL
    # Mail
    - MAIL_SERVICE
    - MAIL_PORT
    - MAIL_HOST
    - MAIL_USER
    - MAIL_PASS
    - MAIL_FROM
    # Security
    - JWT_ACCESS_SECRET
    - JWT_REFRESH_SECRET
    # AWS S3
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_BUCKET_NAME
    - AWS_BUCKET_REGION
    # Solana
    - TREASURY_PRIVATE_KEY
    - TREASURY_SECRET
    - AUCTION_HOUSE_ADDRESS
    - SIGN_MESSAGE
    # Helius
    - HELIUS_API_KEY
    - WEBHOOK_ID

accessories:
  prometheus:
    image: prom/prometheus:latest
    roles:
      - monitoring
    cmd: |
      --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - /var/lib/prometheus:/prometheus
    files:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    options:
      user: root
    labels:
      traefik.http.routers.d-reader-backend-prometheus.rule: Host(`prometheus-dreader.bdeak.net`)
      traefik.http.routers.d-reader-backend-prometheus.middlewares: prometheus-auth
      traefik.http.routers.d-reader-backend-prometheus-metrics.rule: Host(`prometheus-dreader.bdeak.net`) && PathPrefix(`/metrics`)
      traefik.http.middlewares.prometheus-auth.basicauth.users: admin:$apr1$UvJWlU7j$f/dutPyM47ffowAhW8t1n/

  node-exporter:
    image: prom/node-exporter:latest
    roles:
      - web
      - monitoring
    cmd: |
      --path.procfs=/host/proc \
      --path.sysfs=/host/sys \
      --path.rootfs=/rootfs \
      --collector.filesystem.mount-points-exclude="^/(sys|proc|dev|host|etc)($$|/)" \
      --collector.processes
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    port: 9100

  grafana:
    image: grafana/grafana:latest
    roles:
      - monitoring
    volumes:
      - /var/lib/grafana:/var/lib/grafana
    options:
      user: root
    labels:
      traefik.http.routers.d-reader-backend-grafana.rule: Host(`grafana-dreader.bdeak.net`)

traefik:
  args:
    accesslog: true
    accesslog.format: json
    accesslog.fields.headers.defaultmode: keep
    accesslog.fields.headers.names.Authorization: drop
    accesslog.fields.headers.names.Cookie: drop
    metrics.prometheus: true
    api.dashboard: true
  options:
    publish:
      - 8080:8080
  labels:
    traefik.http.routers.dashboard.entrypoints: traefik
    traefik.http.routers.dashboard.rule: PathPrefix(`/api`, `/dashboard`)
    traefik.http.routers.dashboard.service: api@internal
    traefik.http.routers.dashboard.middlewares: traefik-auth
    traefik.http.middlewares.traefik-auth.basicauth.users: admin:$apr1$MmIhxigx$PFHwq/Sm1an1Bzosw1sIL1
    # command to generate new password: htpasswd -n admin

healthcheck:
  path: /app/healthcheck
  port: 3005
  max_attempts: 10

audit_broadcast_cmd: config/scripts/mrsk-audit-broadcast.sh
