global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: grafana
    static_configs:
      - targets:
          - grafana-dreader.bdeak.net

  - job_name: loki
    static_configs:
      - targets:
          - loki-dreader.bdeak.net

  - job_name: traefik
    static_configs:
      - targets:
          - 49.12.3.58:8080 # dev-devnet
          - 91.107.218.131:8080 # dev-mainnet
          - 168.119.158.168:8080 # monitoring

  - job_name: node
    static_configs:
      - targets:
          - 49.12.3.58:9100 # dev-devnet
          - 91.107.218.131:9100 # dev-mainnet
          - 168.119.158.168:9100 # monitoring
