global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: grafana
    static_configs:
      - targets:
          - grafana-dreader.bdeak.net

  - job_name: loki
    static_configs:
      - targets:
          - loki-dreader.bdeak.net

  - job_name: traefik
    static_configs:
      - targets:
          - 54.91.186.17:8080 # dev-devnet
          - 174.129.59.220:8080 # dev-mainnet
          - 18.208.225.125:8080 # monitoring

  - job_name: node
    static_configs:
      - targets:
          - 54.91.186.17:9100 # dev-devnet
          - 174.129.59.220:9100 # dev-mainnet
          - 18.208.225.125:9100 # monitoring
