name: Deploy

on:
  push:
    branches:
      - dev
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        solana-cluster: [devnet, mainnet]
      fail-fast: false

    environment:
      name: ${{ github.ref_name }}-${{ matrix.solana-cluster }}
      url: https://api-${{ github.ref_name }}-${{ matrix.solana-cluster }}.dreader.io

    concurrency:
      group: ${{ github.ref_name }}-${{ matrix.solana-cluster }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true

      - name: Setup mrsk
        run: |
          gem install mrsk

      - name: Setup sops
        uses: mdgreenwald/mozilla-sops-action@v1.4.1

      - name: Setup age
        run: |
          mkdir -p ~/.config/sops/age
          echo "$AGE_SECRET_KEY" > ~/.config/sops/age/keys.txt
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}

      - name: Setup ssh-agent
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Run mrsk
        run: |
          ./config/scripts/mrsk.sh $ENV lock release
          ./config/scripts/mrsk.sh $ENV deploy --roles web
        env:
          ENV: ${{ github.ref_name }}-${{ matrix.solana-cluster }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
