name: Deploy

on:
  push:
    branches:
      - dev
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        solana-cluster: [devnet]

    environment:
      name: ${{ github.ref_name }}-${{ matrix.solana-cluster }}
      url: ${{ steps.environment.outputs.url }}

    concurrency:
      group: ${{ github.ref_name }}-${{ matrix.solana-cluster }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment
        id: environment
        run: |
          echo "url=$(./config/scripts/api-url.sh $GIT_BRANCH $SOLANA_CLUSTER)" >> $GITHUB_OUTPUT
        env:
          GIT_BRANCH: ${{ github.ref_name }}
          SOLANA_CLUSTER: ${{ matrix.solana-cluster }}

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Setup mrsk
        run: |
          gem install mrsk

      - name: Setup sops
        uses: mdgreenwald/mozilla-sops-action@v1.4.1

      - name: Setup age
        run: |
          mkdir -p ~/.config/sops/age
          echo "$AGE_SECRET_KEY" > ~/.config/sops/age/keys.txt
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}

      - name: Setup ssh-agent
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Run mrsk
        run: |
          ./config/scripts/mrsk.sh $ENV deploy --roles web
        env:
          ENV: ${{ github.ref_name }}-${{ matrix.solana-cluster }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
